---
- hosts: all
  gather_facts: False
  vars:
    app_version: "1.0.0"

  pre_tasks:
    - name: Check if Python binary is present
      raw: "test -e /usr/bin/python || (apt -q=2 update && apt -q=2 -y install python)"
      become: True
    - name: Gather facts
      setup:

  tasks:
    - name: Install the Docker package
      apt:
        name: ["docker.io", "python-docker"]
        update_cache: yes
        cache_valid_time: "1200"
      become: True
    - name: Download the 'weather-app' Docker image
      docker_image:
        name: "ivuk/weather-app:{{ app_version }}"
        source: "pull"
      become: True
    - name: Copy 'daemon.json' to /etc/docker/
      copy: src=files/daemon.json dest=/etc/docker/daemon.json owner=root group=root mode=0644
      become: True
      notify:
          - Restart 'docker' service
  handlers:
    - name: Restart 'docker' service
      service: name=docker state=restarted
      become: True
